package:
  name: vlfeat
  version: "0.9.20"

source:
  fn: vlfeat-0.9.20-bin.tar.gz
  url: http://www.vlfeat.org/download/vlfeat-0.9.20-bin.tar.gz

  patches:
    - no_test.patch  # [unix]

requirements:
  build:
    - python
  
  run:
    - python

build:
  features:
    - vc9   # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]

test:
  commands: 
    - sift -h      # [unix]
    - ..\..\envs\_test\Library\bin\sift.exe -h  # [win]
about:
  home: http://www.vlfeat.org/
  license: BSD
